### ISSUE TITLE
Email archiving failed

### ISSUE THREAD

**Issue by blackdog70** [vnc-biz/zcs-openerp-connector#3]
Hi,
I've downloaded zmpkg from http://packages.vnc.biz/zmpkg/bootstrap/zmpkg-installer-1.4.2.0.tar.gz

and its installation seems ok.

After that 

zm-apt-get update
zm-apt-get upgrade

zm-apt-get update
zm-apt-get install zcs-openerp-connector
zmmailboxdctl restart

and in zimbra the connector seem to be installed correctly.

Also the installation of modules in openerp seems ok.
And also the connection from zimbra to openerp is ok.

But after trying a push I get a dialog that show a "Email archiving failed" and the log in /opt/zimbra/log/zmmailboxd.out contain the following error

4090,008: Total time for which application threads were stopped: 0,0005760 seconds
4090,038: Total time for which application threads were stopped: 0,0003630 seconds
INFO [OpenERPConnector] Going to call histary_message from sendMail
INFO [OpenERPConnector] Calling XMLRPC service: http://openerp:8069/xmlrpc/object
ERROR [OpenERPConnector] Archive email failed java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at redstone.xmlrpc.XmlRpcStruct.getInteger(XmlRpcStruct.java:92)
    at redstone.xmlrpc.XmlRpcClient.handleResponse(XmlRpcClient.java:390)
    at redstone.xmlrpc.XmlRpcClient.endCall(XmlRpcClient.java:332)
    at redstone.xmlrpc.XmlRpcClient.invoke(XmlRpcClient.java:190)
    at biz.vnc.zimbra.openerp_zimlet.Connector.rpc_call_object(Connector.java:69)
    at biz.vnc.zimbra.openerp_zimlet.Connector.rpc_call_object_execute(Connector.java:80)
    at biz.vnc.zimbra.openerp_zimlet.Connector.sendMail(Connector.java:235)
    at org.apache.jsp.com_005fzimbra_005ferp_005fmail_005fconnector.PushEmail_jsp._jspService(org.apache.jsp.com_005fzimbra_005ferp_005fmail_005fconnector.PushEmail_jsp:73)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:403)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:476)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:366)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:654)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:445)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:574)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:293)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:120)
    at com.zimbra.cs.zimlet.ZimletResources.service(ZimletResources.java:132)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:654)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1320)
    at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:52)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
    at com.zimbra.cs.zimlet.ZimletFilter.doFilter(ZimletFilter.java:240)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
    at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:57)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:82)
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:268)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
    at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter(ETagHeaderFilter.java:45)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
    at com.zimbra.cs.servlet.ThrottlingFilter.doFilter(ThrottlingFilter.java:71)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
    at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:114)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
    at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:474)
    at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:345)
    at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:316)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:556)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:317)
    at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:81)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:369)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:744)
4095,045: Total time for which application threads were stopped: 0,0003850 seconds
4095,045: Total time for which application threads were stopped: 0,0004780 seconds
4095,046: Total time for which application threads were stopped: 0,0001390 seconds
4103,241: Total time for which application threads were stopped: 0,0005610 seconds
4107,093: Total time for which application threads were stopped: 0,0005110 seconds
4114,094: Total time for which application threads were stopped: 0,0005120 seconds
4117,104: Total time for which application threads were stopped: 0,0005510 seconds
4127,115: Total time for which application threads were stopped: 0,0003730 seconds
4137,527: Total time for which application threads were stopped: 0,0004300 seconds

**Comment by dhaval-vnc** [comment]
Could you please post the openERP error logs as well?

**Comment by dhaval-vnc** [comment]
@blackdog70  Did you install openERP Zimbra connector module in openERP? https://github.com/vnc-biz/openerp-zimbra-connector/tree/master-7.0

Note that the latest zimlet works properly with OpenERP version 7.0. We dropped support of openERP 6 in the latest version.

**Comment by blackdog70** [comment]
Many thanks for your very fast reply.
Today after a restart of openerp server all is working perfectly.
Sorry for bothering you, yesterday a restart was not in my mind because normally this is not necessary with a new module installed.
